# Use a lightweight Python base image
FROM python:3.10-slim

# Set the working directory inside the container
WORKDIR /app

# Install dependencies
COPY ./backend/requirements.txt .
RUN pip install --upgrade pip && \
    pip install -r requirements.txt

# Copy the backend application code
COPY ./backend/app ./app

# Expose the port that the app will run on
EXPOSE 8080

# Command to run the application
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8080"]
